#!/usr/bin/env python

import rospy

rospy.init_node('talker', anonymous=True)
host = rospy.get_param('~host', 'x.x.x.x')
port = rospy.get_param('~port', 3000)

rospy.logwarn("Got params {} {}".format(host, port))
